# Generated by Django 6.0.4 on 2026-04-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("duration", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="tours/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
